use Autotools on non-Windows builds.
conda-forge/yaml-feedstock pull request #14
Opened 2019-12-02 20:08 UTC by seanyen

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This fixes #13

2019-12-02 20:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2019-12-02 20:29 UTC, mbargull requested changes
Only small remarks, but generally, this works on a local build:
```sh
ls -lA lib/*.so*
lrwxrwxrwx 1 conda conda     18 Dec  2 20:26 lib/libyaml-0.so.2 -> libyaml-0.so.2.0.6
-rwxrwxr-x 1 conda conda 125064 Dec  2 20:26 lib/libyaml-0.so.2.0.6
lrwxrwxrwx 1 conda conda     18 Dec  2 20:26 lib/libyaml.so -> libyaml-0.so.2.0.6
```

Thanks!

2019-12-02 20:29 UTC, mbargull commented on recipe/meta.yaml
>      - cmake
You can add the `[win]` selector to `cmake`, `pkg-config`, `ninja`.

2019-12-02 20:29 UTC, mbargull commented on recipe/meta.yaml
>      - vs2017_win-32                      # [win32]
```suggestion
```
We generally don't support `win32` anymore.

2019-12-02 20:29 UTC, mbargull commented on recipe/meta.yaml
>      - vs2017_win-64                      # [win64]
Does this really need 2017 or is 2015 fine, too? If 2015 works, we can use `{{ compiler('c') }}` on all platforms.

2019-12-02 20:29 UTC, mbargull commented on recipe/meta.yaml
>      - vs2017_win-64                      # [win64]
Also, this is C-only, right? Then please remove `{{ compiler('cxx') }}`.

2019-12-02 21:39 UTC, seanyen commented
@mbargull Thanks for the comments. I fixed them and let's wait for the CI result.

2019-12-02 23:08 UTC, merged

2019-12-03 07:48 UTC, mbargull reviewed
Looks good, thanks @seanyen!